export const columns = [
  {
    label: "业态",
    key: "projectType",
    width: "2rem",
    fixed: true,
    align: "left",
  },
  {
    label: "主要指标",
    key: "subjectName",
    width: "2.4rem",
    fixed: true,
    align: "left",
  },
  {
    label: "2020年度预计发生额",
    key: "preYearBudget",
    width: "4.7333rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "2021年度预算合计",
    key: "preYearBudget",
    width: "4.7333rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "一季度",
    key: "budgetQaOne",
    group: "2021年预算",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "二季度",
    key: "budgetQaTwo",
    group: "2021年预算",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "三季度",
    key: "budgetQaThree",
    group: "2021年预算",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "四季度",
    key: "budgetQaFour",
    group: "2021年预算",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "合计",
    key: "budgetTotal",
    group: "2021年预算",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "21VS20增长率",
    key: "increasePre",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "2022年预算",
    key: "nextYearBudget",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "22VS21增长率",
    key: "increaseNext",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "2023年预算",
    key: "nextTwoYearBudget",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
  {
    label: "23VS22增长率",
    key: "increaseNextTwo",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
    unit: "%",
  },
];