export default {
  // chartCode: state => state.chartCode,
  rentList: state => state.rentList,
  wgPayWayList: state => state.wgPayWayList,
  cyclePayWayList: state => state.cyclePayWayList,
  cyclePayWayStoreList: state => state.cyclePayWayStoreList,
  sellWayList: state => state.sellWayList,
  bizList: state => state.bizList,
  contractTypeList: state => state.contractTypeList,
  houseTypeList: state => state.houseTypeList,
  storeChargeTypeList: state => state.storeChargeTypeList,
  storeTypeList: state => state.storeTypeList,
  multiTypeList: state => state.multiTypeList,
  saleInitialStatusList: state => state.saleInitialStatusList,
  houseTypeList: state => state.houseTypeList,
  layoutCdList: state => state.layoutCdList,
  oweTypeList: state => state.oweTypeList,
  contTypeList: state => state.contTypeList,
  zxMultiTypeList: state => state.zxMultiTypeList,
  chargeTypeList: state => state.chargeTypeList,
  wyBizTypeList: state => state.wyBizTypeList,
  companyName: state => state.companyName,
  currentYear: state => { return new Date().getFullYear() },
  currentYearNumber: state => { var year = '' + new Date().getFullYear(); return Number(year.substr(2)) },
  getBudgetYear: state => state.budgetYear,
  getBudgetYearNumber: state => { let budgetYearStr = `${state.budgetYear}`; let budgetYearNumber = Number(budgetYearStr.substr(2)); return budgetYearNumber }
}
