export const columns = [
  {
    label: "收入类别",
    key: "incomeType",
    width: "1.86rem",
    align: "left",
  },
  {
    label: "业态",
    key: "bizType",
    width: "1.86rem",
    align: "left",
  },
  {
    label: "类别",
    key: "rentType",
    width: "1.966rem",
    align: "left",
  },
  {
    label: "2021年应收",
    key: "receivableNextYear",
    group: "合计",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "年计费面积",
    key: "areaNextYear",
    group: "合计",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "单价(元/月/(m²))",
    key: "priceNextYear",
    group: "合计",
    width: "3.9333rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "1月",
    key: "receivableJan",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "2月",
    key: "receivableFeb",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "3月",
    key: "receivableMarch",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "4月",
    key: "receivableApril",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "5月",
    key: "receivableMay",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "6月",
    key: "receivableJune",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "7月",
    key: "receivableJuly",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "8月",
    key: "receivableAugust",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "9月",
    key: "receivableSep",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "10月",
    key: "receivableOct",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "11月",
    key: "receivableNove",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "12月",
    key: "receivableDece",
    group: "应收",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "1月",
    key: "areaJan",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "2月",
    key: "areaFeb",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "3月",
    key: "areaMarch",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "4月",
    key: "areaApril",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "5月",
    key: "areaMay",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "6月",
    key: "areaJune",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "7月",
    key: "areaJuly",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "8月",
    key: "areaAugust",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "9月",
    key: "areaSep",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "10月",
    key: "areaOct",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "11月",
    key: "areaNove",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "12月",
    key: "areaDece",
    group: "计费面积",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "2021年应收",
    key: "receivableNextTwoYear",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "2022年应收",
    key: "receivableNextThreeYear",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
];
