export const columns = [
  {
    label: "业态",
    key: "bizType",
    width: "1.8rem",
    align: "left",
  },
  {
    label: "资产",
    key: "assetType",
    width: "1.8rem",
    align: "left",
  },
  {
    label: "属性",
    key: "assetNature",
    width: "2rem",
    align: "left",
  },
  {
    label: "建筑面积(m²)",
    key: "coveredArea",
    width: "3.0rem",
    group: "管理面积",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "套内面积(m²)",
    key: "insideArea",
    width: "3.0rem",
    group: "管理面积",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "一铺一价版",
    key: "glaPriceArea",
    width: "3.0rem",
    group: "GLA(可租面积)",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "签约版",
    key: "glaContractArea",
    width: "3.0rem",
    group: "GLA(可租面积)",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "签约版",
    key: "billingArea",
    width: "3.0rem",
    group: "计费面积",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "车位数",
    key: "parkingNum",
    width: "3.0rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "免费时长(h)",
    key: "ratesFreetime",
    width: "2.6667rem",
    group: "收费标准",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "收费标准(元/h)",
    key: "ratesHour",
    width: "2.9667rem",
    group: "收费标准",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "24H封顶(元)",
    key: "ratesDay",
    width: "2.6667rem",
    group: "收费标准",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "员工停车(元/月)",
    key: "ratesEmp",
    width: "3.1333rem",
    group: "收费标准",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
];
