export const columns = [
  {
    label: "资金方向",
    key: "subjectLevelOne",
    width: "2.67rem",
    align: "left",
  },
  {
    label: "项目",
    key: "subjectLevelTwo",
    width: "2.67rem",
    align: "left",
  },
  {
    label: "1月预算数",
    key: "budgetJan",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "2月预算数",
    key: "budgetFeb",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "3月预算数",
    key: "budgetMarch",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "4月预算数",
    key: "budgetApril",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "5月预算数",
    key: "budgetMay",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "6月预算数",
    key: "budgetJune",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "7月预算数",
    key: "budgetJuly",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "8月预算数",
    key: "budgetAug",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "9月预算数",
    key: "budgetSep",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "10月预算数",
    key: "budgetOct",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "11月预算数",
    key: "budgetNov",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
  {
    label: "12月预算数",
    key: "budgetDece",
    width: "3.6667rem",
    align: "right",
    numberPrecision: 2,
    numberFormat: true,
  },
];