const yearColumns = [
    {
        label: "序号",
        width: "1.2rem",
    },
    {
        label: "项目",
        key: "projectName",
        color: "#3992BA",
        width: "2rem",
        align: "left",
    },
    {
        label: "客流密度",
        key: "passengerFlowDensity",
        sortable: true,
        width: "2.3rem",
        align: "right",
        numberFormat: true,
        numberPrecision: 2,
    },
    {
        label: "客流(万人)",
        key: "passengerFlow",
        width: "2.8rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "growth",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: "%",
        numberPrecision: 2,
    },
    {
        label: "达成率",
        key: "achievementRate",
        width: "2rem",
        sortable: true,
        align: "right",
        unit: "%",
        numberPrecision: 2,
    },
];
const monthColumns = [
    {
        label: "序号",
        width: "1.2rem",
    },
    {
        label: "项目",
        key: "projectName",
        color: "#3992BA",
        width: "2rem",
        align: "left",
    },
    {
        label: "客流密度",
        key: "passengerFlowDensity",
        sortable: true,
        width: "2.3rem",
        align: "right",
        numberFormat: true,
        numberPrecision: 2,
    },
    {
        label: "客流(万人)",
        key: "passengerFlow",
        width: "2.8rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "growth",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: "%",
        numberPrecision: 2,
    },
    {
        label: "达成率",
        key: "achievementRate",
        width: "2rem",
        sortable: true,
        align: "right",
        unit: "%",
        numberPrecision: 2,
    },
];
const dayColumns = [
    {
        label: "序号",
        width: "1.2rem",
        fixed: true,
    },
    {
        label: "项目",
        key: "projectName",
        color: "#3992BA",
        width: "2rem",
        align: "left",
        fixed: true,
    },
    {
        label: "当日客流(万)",
        key: "todayPassengerFlow",
        sortable: true,
        width: "3.2rem",
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "昨日客流(万)",
        key: "yesterdayPassengerFlow",
        sortable: true,
        width: "3.2rem",
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "昨日环比",
        key: "growth",
        width: "2.3rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
];

export { yearColumns, monthColumns, dayColumns }