
const yearColumns = [
    {
        label: "月份",
        key: "month",
        width: "2.1rem",
        align: "left",
    },
    {
        label: "客流",
        key: "cumulativeActualFlowOfMonth",
        sortable: true,
        width: "1.6rem",
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "日均客流",
        key: "averageDailyPassengerFlow",
        width: "2.3rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "yearOnYear",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: "%",
        numberPrecision: 2,
    },
    {
        label: "达成率",
        key: "achievementRateOfYear",
        width: "1.9rem",
        sortable: true,
        align: "right",
        unit: "%",
        numberPrecision: 2,
    },
];
const monthColumns = [
    {
        label: "月份",
        key: "month",
        width: "2.1rem",
        align: "left",
    },
    {
        label: "工作日",
        key: "workdayPassengerFlow",
        sortable: true,
        width: "1.9rem",
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "节假日",
        key: "holidayPassengerFlow",
        width: "1.9rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "客流密度",
        key: "passengerFlowDensity",
        width: "2.3rem",
        sortable: true,
        align: "right",
        numberPrecision: 2,
    },
    {
        label: "日均客流",
        key: "averageDailyPassengerFlow",
        width: "2.3rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "客流",
        key: "actualFlowOfMonth",
        width: "1.6rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "monthOnMonth",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: "%",
        numberPrecision: 2,
    },
    {
        label: "达成率",
        key: "achievementRate",
        width: "1.9rem",
        sortable: true,
        align: "right",
        unit: "%",
        numberPrecision: 2,
    },
];
export { yearColumns, monthColumns }