// 租金收入 - 列表 - 月 - 表头
const yueColumnsZJ = [
    {
        label: "序号",
        width: "1.2rem",
    },
    {
        label: "项目",
        key: "name",
        color: "#3992BA",
        align: "left",
        width: "2rem",
    },
    {
        label: "应收(万)",
        key: "contMustMoney",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收入(万)",
        key: "fixedFactMoney",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRate",
        width: "2.6667rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTb",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "收缴率(权责)",
        key: "fixedQzCollectionRate",
        width: "2.7rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "fixedQzCollectionRateHb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "fixedQzCollectionRateTb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "月预算完成进度",
        key: "fixedQzCompletionRate",
        width: "3.1rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]
// 租金收入 - 列表 - 年 - 表头
const nianColumnsZJ = [
    {
        label: "序号",
        width: "1.2rem",
    },
    {
        label: "项目",
        key: "name",
        color: "#3992BA",
        align: "left",
        width: "2rem",
    },
    {
        label: "应收(万)",
        key: "contMustMoneyYtd",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收入(万)",
        key: "fixedFactMoneyYtd",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRateYtd",
        width: "2.6667rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHbYtd",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTbYtd",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "收缴率(权责)",
        key: "fixedQzCollectionRateYtd",
        width: "2.6667rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "fixedQzCollectionRateHbYtd",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "qzCollectionRateTbYtd",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "年预算完成进度",
        key: "fixedQzCompletionRateYtd",
        width: "3.1rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]

// 物管收入 - 列表 - 月 - 表头
const yueColumnsWG = [
    {
        label: "序号",
        width: "1.2rem",
    },
    {
        label: "项目",
        key: "name",
        color: "#3992BA",
        align: "left",
        width: "2rem",
    },
    {
        label: "应收(万)",
        key: "contMustMoney",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收入(万)",
        key: "fixedFactMoney",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRate",
        width: "2.6667rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTb",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "收缴率(权责)",
        key: "fixedQzCollectionRate",
        width: "2.6667rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "fixedQzCollectionRateHb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "fixedQzCollectionRateTb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "月预算完成进度",
        key: "fixedQzCompletionRate",
        width: "3.1rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]
// 物管收入 - 列表 - 年 - 表头
const nianColumnsWG = [
    {
        label: "序号",
        width: "1.2rem",
    },
    {
        label: "项目",
        key: "name",
        color: "#3992BA",
        align: "left",
        width: "2rem",
    },
    {
        label: "应收(万)",
        key: "contMustMoneyYtd",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收入(万)",
        key: "fixedFactMoneyYtd",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRateYtd",
        width: "2.6667rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHbYtd",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTbYtd",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "收缴率(权责)",
        key: "fixedQzCollectionRateYtd",
        width: "2.6667rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "fixedQzCollectionRateHbYtd",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "qzCollectionRateTbYtd",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "年预算完成进度",
        key: "fixedQzCompletionRateYtd",
        width: "3.1rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]

// 多经收入 - 列表 - 月 - 表头
const yueColumnsDJ = [
    {
        label: "序号",
        width: "1.2rem",
    },
    {
        label: "项目",
        key: "name",
        color: "#3992BA",
        align: "left",
        width: "2rem",
    },
    {
        label: "应收(万)",
        key: "contMustMoney",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收入(万)",
        key: "fixedFactMoney",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRate",
        width: "2.6667rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "月预算完成进度",
        key: "fixedQzCompletionRate",
        width: "3.1rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]
// 多经收入 - 列表 - 年 - 表头
const nianColumnsDJ = [
    {
        label: "序号",
        width: "1.2rem",
    },
    {
        label: "项目",
        key: "name",
        color: "#3992BA",
        align: "left",
        width: "2rem",
    },
    {
        label: "应收(万)",
        key: "contMustMoneyYtd",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收入(万)",
        key: "fixedFactMoneyYtd",
        width: "2.2rem",
        sortable: true,
        align: "right",
        numberFormat: true,
        changeNum: 10000,
        numberPrecision: 2,
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRateYtd",
        width: "2.6667rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHbYtd",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTbYtd",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "年预算完成进度",
        key: "fixedQzCompletionRateYtd",
        width: "3.1rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    }
]




// 租金收入、项目详情 - 月 - 表头
const yueProjectColumnsZJ = [
    {
        label: "月份",
        key: "yearMonth",
        align: "left",
        width: "2rem",
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRate",
        width: "2.9333rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTb",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "收缴率(权责)",
        key: "fixedQzCollectionRate",
        width: "2.9333rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "fixedQzCollectionRateHb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "fixedQzCollectionRateTb",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]
// 租金收入、项目详情 - 年 - 表头
const nianProjectColumnsZJ = [
    {
        label: "月份",
        key: "yearMonth",
        align: "left",
        width: "2rem",
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRateYtd",
        width: "2.9333rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHbYtd",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTbYtd",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "收缴率(权责)",
        key: "fixedQzCollectionRateYtd",
        width: "2.9333rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "fixedQzCollectionRateHbYtd",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "fixedQzCompletionRateTbYtd",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]

// 物管收入、项目详情 - 月 - 表头
const yueProjectColumnsWG = [
    {
        label: "月份",
        key: "yearMonth",
        align: "left",
        width: "2rem",
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRate",
        width: "2.9333rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTb",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "收缴率(权责)",
        key: "fixedQzCollectionRate",
        width: "2.9333rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "fixedQzCollectionRateHb",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "fixedQzCollectionRateTb",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]
// 物管收入、项目详情 - 年 - 表头
const nianProjectColumnsWG = [
    {
        label: "月份",
        key: "yearMonth",
        align: "left",
        width: "2rem",
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRateYtd",
        width: "2.9333rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "contCollectionRateHbYtd",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTbYtd",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "收缴率(权责)",
        key: "fixedQzCollectionRateYtd",
        width: "2.9333rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "环比",
        key: "fixedQzCollectionRateHbYtd",
        width: "1.8rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "fixedQzCompletionRateTbYtd",
        width: "1.6rem",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]



// 多经收入 项目详情 - 月 - 表头
const yueProjectColumnsDJ = [
    {
        label: "月份",
        key: "yearMonth",
        align: "left",
        width: "2rem",
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRate",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateTb",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]
// 多经收入 项目详情 - 年 - 表头
const nianProjectColumnsDJ = [
    {
        label: "月份",
        key: "yearMonth",
        align: "left",
        width: "2rem",
    },
    {
        label: "收缴率(合同)",
        key: "fixedContCollectionRateYtd",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
    {
        label: "同比",
        key: "contCollectionRateHbYtd",
        sortable: true,
        align: "right",
        unit: '%',
        numberPrecision: 2,
    },
]


export { yueColumnsZJ, nianColumnsZJ, yueColumnsWG, nianColumnsWG, yueColumnsDJ, nianColumnsDJ, yueProjectColumnsZJ, nianProjectColumnsZJ, yueProjectColumnsWG, nianProjectColumnsWG, yueProjectColumnsDJ, nianProjectColumnsDJ };