export const projectPageMap = {
  68: ['资金计划', '/pages/yusuan/zjjh/index', 68],
  69: ['基础信息表_面积信息', '/pages/yusuan/mjxx/index', 69],
  70: ['主要指标表', '/pages/yusuan/zyzb/index', 70],
  71: ['租费概况表', '/pages/yusuan/zfgk/index', 71],
  72: ['人事费用概况-人事费用', '/pages/yusuan/rsfy/index', 72],
  73: ['行政费用概况', '/pages/yusuan/xzfy/index', 73],
  74: ['企划费', '/pages/yusuan/qhf/index', 74],
  75: ['能耗费概况', '/pages/yusuan/nhf/index', 75],
  76: ['地产支付物业款项统计', '/pages/yusuan/dczf/index', 76],
  77: ['物业新增交房统计', '/pages/yusuan/wyxzjf/index', 77],
  78: ['基础信息表_项目信息', '/pages/yusuan/xmxx/index', 78],
  79: ['基础信息表_人员信息', '/pages/yusuan/ryxx/index', 79],
  80: ['人事费用概况-人数概况', '/pages/yusuan/rsgk/index', 80],
}